# Advanced Audit & Row-Level Security
**Domain:** Audit
**Layer:** Security

```mermaid
erDiagram
  AUDIT_POLICY {
    UUID id PK                        "NOT NULL; UNIQUE"
    ENUM entity_type                  "NOT NULL; CHECK (entity_type IN ('USER', 'WORKOUT', 'EXERCISE', 'PROGRAM', 'INSTITUTION', 'PAYMENT', 'SUBSCRIPTION', 'MEDIA', 'EQUIPMENT', 'ROLE', 'PERMISSION'))"
    ENUM action_type                  "NOT NULL; CHECK (action_type IN ('CREATE', 'UPDATE', 'DELETE', 'VIEW', 'EXPORT', 'SHARE', 'ARCHIVE', 'RESTORE', 'LOGIN', 'LOGOUT'))"
    BOOLEAN is_enabled                "NOT NULL; DEFAULT true"
    BOOLEAN track_old_values          "NOT NULL; DEFAULT true"
    BOOLEAN track_new_values          "NOT NULL; DEFAULT true"
    BOOLEAN track_field_changes       "NOT NULL; DEFAULT true"
    JSONB excluded_fields             "NULLABLE"
    JSONB sensitive_fields            "NULLABLE"
    SMALLINT retention_days           "NOT NULL; DEFAULT 2555; CHECK (retention_days > 0)"
    BOOLEAN requires_approval         "NOT NULL; DEFAULT false"
    ENUM compression_strategy         "NOT NULL; DEFAULT 'NONE'; CHECK (compression_strategy IN ('NONE', 'GZIP', 'LZ4', 'ZSTD'))"
    SMALLINT compress_after_days      "NULLABLE; CHECK (compress_after_days > 0)"
    UUID created_by FK                "NOT NULL; references USER.id"
    UUID updated_by FK                "NULLABLE; references USER.id"
    TIMESTAMP created_at              "NOT NULL; DEFAULT now()"
    TIMESTAMP updated_at              "NOT NULL; DEFAULT now()"
    BOOLEAN is_active                 "NOT NULL; DEFAULT true"
    UNIQUE entity_action_policy       "(entity_type, action_type)"
    INDEX idx_audit_policy_entity     "(entity_type, is_enabled)"
  }
  
  ROW_LEVEL_POLICY {
    UUID id PK                        "NOT NULL; UNIQUE"
    VARCHAR(100) table_name           "NOT NULL"
    VARCHAR(100) policy_name          "NOT NULL"
    ENUM policy_type                  "NOT NULL; CHECK (policy_type IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE', 'ALL'))"
    TEXT policy_expression            "NOT NULL; CHECK (LENGTH(policy_expression) <= 2000)"
    ENUM target_role                  "NOT NULL; CHECK (target_role IN ('PUBLIC', 'AUTHENTICATED_USER', 'INSTITUTION_MEMBER', 'ADMIN', 'SYSTEM'))"
    BOOLEAN is_enabled                "NOT NULL; DEFAULT true"
    BOOLEAN is_permissive             "NOT NULL; DEFAULT true"
    TEXT description                  "NULLABLE; CHECK (LENGTH(description) <= 1000)"
    JSONB policy_configuration        "NULLABLE"
    UUID created_by FK                "NOT NULL; references USER.id"
    UUID updated_by FK                "NULLABLE; references USER.id"
    TIMESTAMP created_at              "NOT NULL; DEFAULT now()"
    TIMESTAMP updated_at              "NOT NULL; DEFAULT now()"
    BOOLEAN is_active                 "NOT NULL; DEFAULT true"
    UNIQUE table_policy_name          "(table_name, policy_name)"
    INDEX idx_rls_policy_table        "(table_name, policy_type, is_enabled)"
  }
  
  SECURITY_CONTEXT {
    UUID id PK                        "NOT NULL; UNIQUE"
    UUID session_id FK                "NOT NULL; references AUDIT_SESSION.session_id"
    UUID user_id FK                   "NULLABLE; references USER.id"
    UUID institution_id FK            "NULLABLE; references INSTITUTION.id"
    UUID department_id FK             "NULLABLE; references INSTITUTION_DEPARTMENT.id"
    JSONB effective_roles             "NOT NULL"
    JSONB effective_permissions       "NOT NULL"
    JSONB context_variables           "NULLABLE"
    BOOLEAN is_elevated               "NOT NULL; DEFAULT false"
    TEXT elevation_reason             "NULLABLE; CHECK (LENGTH(elevation_reason) <= 500)"
    TIMESTAMP elevation_expires_at    "NULLABLE"
    UUID elevated_by FK               "NULLABLE; references USER.id"
    UUID created_by FK                "NOT NULL; references USER.id"
    TIMESTAMP created_at              "NOT NULL; DEFAULT now()"
    TIMESTAMP updated_at              "NOT NULL; DEFAULT now()"
    BOOLEAN is_active                 "NOT NULL; DEFAULT true"
    INDEX idx_security_context_session "(session_id, is_active)"
    INDEX idx_security_context_user   "(user_id, is_elevated, is_active)"
    INDEX idx_security_context_elevation "(elevation_expires_at) WHERE is_elevated = true"
  }
  
  AUDIT_AUTOMATION_TRIGGER {
    UUID id PK                        "NOT NULL; UNIQUE"
    VARCHAR(100) trigger_name         "NOT NULL; UNIQUE"
    VARCHAR(100) table_name           "NOT NULL"
    ENUM trigger_timing               "NOT NULL; CHECK (trigger_timing IN ('BEFORE', 'AFTER', 'INSTEAD_OF'))"
    ENUM trigger_event                "NOT NULL; CHECK (trigger_event IN ('INSERT', 'UPDATE', 'DELETE', 'TRUNCATE'))"
    TEXT trigger_function             "NOT NULL; CHECK (LENGTH(trigger_function) <= 100)"
    BOOLEAN capture_old_values        "NOT NULL; DEFAULT true"
    BOOLEAN capture_new_values        "NOT NULL; DEFAULT true"
    BOOLEAN async_processing          "NOT NULL; DEFAULT false"
    JSONB trigger_configuration       "NULLABLE"
    BOOLEAN is_enabled                "NOT NULL; DEFAULT true"
    UUID created_by FK                "NOT NULL; references USER.id"
    UUID updated_by FK                "NULLABLE; references USER.id"
    TIMESTAMP created_at              "NOT NULL; DEFAULT now()"
    TIMESTAMP updated_at              "NOT NULL; DEFAULT now()"
    BOOLEAN is_active                 "NOT NULL; DEFAULT true"
    INDEX idx_audit_trigger_table     "(table_name, trigger_event, is_enabled)"
  }

  AUDIT_POLICY ||--o{ AUDIT_LOG : "policy_enforcement"
  ROW_LEVEL_POLICY ||--o{ SECURITY_CONTEXT : "policy_context"
  SECURITY_CONTEXT }|--|| AUDIT_SESSION : "session_lookup"
  SECURITY_CONTEXT }o--|| USER : "user_context"
  SECURITY_CONTEXT }o--|| INSTITUTION : "institution_context"
  SECURITY_CONTEXT }o--|| INSTITUTION_DEPARTMENT : "department_context"
  SECURITY_CONTEXT }o--|| USER : "elevated_by"
  AUDIT_AUTOMATION_TRIGGER ||--o{ AUDIT_LOG : "automated_capture"
  AUDIT_POLICY }|--|| USER : "created_by"
  AUDIT_POLICY }o--|| USER : "updated_by"
  ROW_LEVEL_POLICY }|--|| USER : "created_by"
  ROW_LEVEL_POLICY }o--|| USER : "updated_by"
  SECURITY_CONTEXT }|--|| USER : "created_by"
  AUDIT_AUTOMATION_TRIGGER }|--|| USER : "created_by"
  AUDIT_AUTOMATION_TRIGGER }o--|| USER : "updated_by"
```