/**
 * Metrics for tracking progress
 */
export enum ProgressMetric {
  WEIGHT = 'WEIGHT',
  REPS = 'REPS',
  TIME = 'TIME',
  DISTANCE = 'DISTANCE',
  HEART_RATE = 'HEART_RATE',
  PAIN_LEVEL = 'PAIN_LEVEL',
  SATISFACTION = 'SATISFACTION',
  STRENGTH_INDEX = 'STRENGTH_INDEX',
  ENDURANCE_INDEX = 'ENDURANCE_INDEX',
  FLEXIBILITY_SCORE = 'FLEXIBILITY_SCORE',
  BODY_COMPOSITION = 'BODY_COMPOSITION'
}

/**
 * Units of measurement
 */
export enum MeasurementUnit {
  KG = 'KG',
  LBS = 'LBS',
  SECONDS = 'SECONDS',
  MINUTES = 'MINUTES',
  KILOMETERS = 'KILOMETERS',
  MILES = 'MILES',
  BPM = 'BPM',
  PERCENTAGE = 'PERCENTAGE',
  SCALE_1_10 = 'SCALE_1_10',
  INCHES = 'INCHES',
  CENTIMETERS = 'CENTIMETERS'
}

